_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: es
uuid: ed578252-8666-4ae1-8375-8fe6177b952b
name: sgdp
mail: pachecoelquis@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: es
mail_notification: ''
