<?php

/**
 * @file
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * Contains fsfb_layouts.module.
 */

/**
 * Implements hook_theme().
 */
function sgdp_core_theme($existing, $type, $theme, $path) {
  return [
    'headerblock' => [
      'template' => 'block/headerblock',
      'variables' => ['title' => NULL, 'data' => NULL],
    ],
    'homecpblock' => [
      'template' => 'block/homecpblock',
      'variables' => ['rol_user' => NULL],
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function sgdp_core_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $current_user = \Drupal::currentUser();

  // Solo ejecuta el unset si el usuario **no** tiene el rol 'administrator'.
  if (!$current_user->hasRole('administrator')) {
    if ($form['#id'] == 'user-register-form') {
      unset($form['field_clientes_asignados']);
      unset($form['field_proveedores_asignados']);
      unset($form['field_rut']);
    }

    if ($form['#id'] == 'user-form') {
      unset($form['field_clientes_asignados']);
      unset($form['field_proveedores_asignados']);
    }
  }
}
